ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:toc:
:toc-placement!:

.**Table of Contents**
toc::[]

---

= Launchers

== https://www.minecraft.net/en-us/[Default Launcher]

This is the default launcher developed by Mojang themselves. Aptly titled "Minecraft Launcher" .

* Pros :
** Easy to set-up
** Fancy skin changer in-built

* Cons :
** Less Flexible with Mods
** World File Buildup
** Locked with one settings config so you might have difficulty if you want to configure something else out of speedrunning. You manually have to change settings each time per new version you create.

* Setup :
** Download the launcher from https://www.minecraft.net/en-us/[here] (Click the big green `Get Minecraft` Button)
** Open it and login via Mojang or Microsoft (Microsoft log-in isn't implemented as of now so Mojang is the way)
** In Minecraft: Java Edition section > Click on `Installations` which is beside `Play` at the top-left side
** Click on the `⊕ New...` Button .
** Give it a name (e.g; CactusChungus or BadLifeChoices) > Click on the version list and Pick `release 1.16.1`
** To add mods , you need to install Fabric and then create a `mods` folder in the `~/Appdata/Roaming/.minecraft` parent folder and put your mods there. **Check the MODS section below for proper installation details**
** OPTIONAL : If you want to allocate more ram (upto 4 GB is ideal) , you can do so by clicking `More Options` and changing the `2` in `-Xmx2G` to 3 or 4 for 3 GB or 4 GB respectively.

---

== https://multimc.org/[MultiMC]
* Pros: 
** Portable
** Very Modular and has instances based design
** Has proper mod system and auto-install for Forge & Fabric.
** Allows having one settings config per instance so having multiple instances guarantees that no setting meshap happens between them.
** Mods are static and can be `disabled` incase they are unwanted for a particular session.
** Small file usage.

* Cons:
** Multiple instances = Big size in total , if instances are not deleted the MultiMc `instances` folder can get quite big.
** Not Fancy like the Default Launcher.
** Third Party Launcher
** You need something called "B.R.A.I.N" to use it.


* Setup :
** Download the launcher from https://multimc.org/#Download[here] and install it.
** If login screen doesn't pop up, click on the right top side `Profiles` button and click `Manage Accounts` > `Add` in the right pane.
** Close the settings pane if opened, then right click on the empty area and click `Create Instance`
** Name it , and pick `1.16.1` from the list and click OK.
** Next , right click on the 1.16.1 that you named just now 
** Click `Edit Instance` and see in the right pane and hit `Install Fabric`.
** Select the Fabric version with the star in it .
** OPTIONAL: TO allocate more RAM , click on `Settings` then Tick the `Memory` Option and set the amount in megabytes and in multiples of 1024 (so 3 GB would be 3 * 1025 = 3072 etc)
** Next click `Close` at the bottom and again right click on the version and click `Edit Instance`. **Check the MODS section below for proper installation details**
** Now a `Loader Mods` section should appear. Click `Add` in the right pane and select the mods you have downloaded and saved somewhere. Your mods should be activated , to deactivate them -> click on `Disable` in the right pane
** Now hit `Launch` and you are ready to play !

NOTE: In MultiMC if your session icon is a cross , do not worry . You can safely ignore it.

---

= Version

== 1.16.1

* Pros: 
** More enderpearl drops from Piglins.
** Bastions don't have Piglin Brutes.

* Cons
** Not the latest version
** No Optifine.

== 1.9-1.15 (More like 1.14.4 really)

* Pros:

* Cons:
** Longer route
** A tiny bit less perfomant

== Pre 1.9

* Pros:
** Good combat mechancis.
** Good Optimizations

* Cons:
** Considerably long routes.
** Old version.

---

= Allowed Hard-Config Changes: 

== Gamma:

* Want to make your world look bright in dark areas and shinny like the ones you see in speedrun streams ?
**  Open .minecraft/`options.txt` and set `gamma` to 5.0.  

WARNING: Do NOT go over 5.0.

== Subtitles:

* Don't want to get jebaited by Lava sounds ? Here is your option !
** In Minecraft Pause Menu : `Options > Accessibility Settings... > Show Subtitles`

== Planer Fog:
* For the Sodium users , here is how you widen your eyes in the nether !
** In Minecraft Pause Menu : `Options > Video Settings... > Unofficial > Use Planar Fog` and tick on it.

---

= Mods

CAUTION: Do NOT use Fabric API, below listed Modifications do NOT require it and will get your run disqualified if you use it.

== Caffeine MC

* Umbrella term for Sodium, Lithium and Phosphor Mods by legenedary mod maker J3llysquid.
** Allow huge optimization to the game and fix the meshap created by Mojank.
** Allows users to use Planer Fog.
** Default options should be adequate.
** Fabric Mods

=== Download
* https://mrmangohands.github.io/sodium-redirect/[Sodium for 1.16.1]
* https://mrmangohands.github.io/lithium-redirect/[Lithium for 1.16.1]
* https://mrmangohands.github.io/phosphor-redirect/[Phosphor for 1.16.1]

=== Setup: 

* For Default Launcher :
** Download & Install Fabric Mod Loader from https://fabricmc.net/use/[here]
** Downlad the three mods from above link for appropriate versions
** Create a `mods` folder in the `.minecraft` sub-folder in your USER_HOME folder.
** Place the 3 mods in that `mods` folder. 
** Run the game !

* For MultiMC:

** Click `Edit Instance` by right clicking on the selected version and click on `Install Fabric` from the right pane
** Select the fabric version with the star mark beside it.
** Click `Close` and re-open `Edit Instance` page.
** Go to `Loader Mods` Section in the Left Pane > Click `Add` in the right Pane > Select the three mods which you downloaded and saved in some place.
** Should be good to go !

---

== Optifine

* Not allowed in versions for which Caffeine MC mods exists.
** Your runs WILL get disqualified if you use it in 1.16.1 or for a version which has Sodium , Lithium and Phosphor for.
** Allows your game to run faster + Shaders.
** Forge Mod

=== Download
* https://optifine.net/downloads[Optifine]

=== Setup:

* For Default Launcher:
** Simply double click the downloaded file and hit Install.

* For MultiMC:
** Click `Edit Instance` by right clicking on the selected version and click on `Install Forge` from the right pane
** Right click the MultiMC version and hit `Minecraft Folder` make a `mods` folder there. Keep the `mods` folder open
** Put the downloaded Optifine jar file in the `mods` folder and launch the game

---

== LazyDFU

* Allows Faster Minecraft start-up/Loading
** Fabric Mod.

=== Download
* https://modrinth.com/mod/lazydfu/versions[LazyDFU]

=== Setup

<Same as for CaffeineMC>

---

== Krypton
* Networking optimization incase you play on servers. 

=== Download 
* https://mrmangohands.github.io/krypton-redirect[Krypton]

=== Setup
<Same as CaffeineMC>

---

= Timers:

There is a split in timing system because of several issues with how timing a run so there are two possible chrono systems : a) IGT stands for In Game Time and b) RT - (Real Time)

The primary timer used is LiveSplit.

== Download

* https://livesplit.org/downloads/[LiveSplit]

== Setup

* https://www.youtube.com/watch?v=Ij7HDfbv63g[Kohru's Guide on How to set it up]

= Streaming Tools:

* OBS:
** Open BroadCasting Software. Excellent in functionality. Beware, might bite you !

== Download
* https://obsproject.com/[OBS Project]

== Setup
* Any generic youtube setup tutorial would work.

---


= Discords

* https://discord.gg/tDPvR9c[Minecraft Java Speedrunning Discord]
* https://discord.gg/tYpdRSn[Console Edition Speedrunning Discord]
* https://discord.gg/wpy4tXWYQQ[Minecraft Pre 1.9 Speedrun Discord]
* https://discord.gg/jGhNxpd[Minecraft TAS Discord]
* https://discord.gg/EFvygzt[Minecraft 1.16 SSG Discord]
* https://discord.gg/d5PKmBJ[Bedrock Discord]
* https://discord.gg/7P3nqzZ[Monkeys]
